### ISSUE TITLE
Problem with eclipse plugin

### ISSUE THREAD

**Issue by den-gr** [Protelis/Protelis-Parser#299]
I try to use the eclipse plugin for protelis but I get this error:
`java.lang.IllegalStateException: Unresolved proxy http://protelis.org#//ProtelisModule. Make sure the EPackage has been registered.`

**Comment by DanySK** [comment]
How to reproduce?

**Comment by DenGuzawr22** [comment]
Minimal example: 
1. Install Protelis plugin
2. create an Eclipse project
3. In the root create a protelis file, paste the code in file

[ExampleProtelisPluginProblem.zip](https://github.com/Protelis/Protelis-Parser/files/13267754/ExampleProtelisPluginProblem.zip)
![image](https://github.com/Protelis/Protelis-Parser/assets/55553082/70b18913-0bc0-45cd-93a8-58c51508f5f4)

In case of gradle project I get the same error but in different format:
![image](https://github.com/Protelis/Protelis-Parser/assets/55553082/b4c2055f-c643-4c95-8487-c148b2f4fc5c)

**Comment by DanySK** [comment]
This is very anomalous. We should switch to Gradle and use a language server instead of a classic Eclipse plugin

**Comment by DanySK** [comment]
We switched to a language server, the Eclipse plugin is to be considered legacy.
