### ISSUE TITLE
Get drone.io build working for organization

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis-Parser#4]
Currently only Danilo can manage the drone.io build; drone.io is supposed to support organization integration: need to figure out why that's not working and get it fixed.

**Comment by jakebeal** [comment]
drone.io support contacted, waiting for reply.

**Comment by DanySK** [comment]
I have copied my configuration on the organization repo. It apparently builds correctly right now.

**Comment by jakebeal** [comment]
Right: building isn't the problem, drone.io not correctly supporting the Protelis organization is the problem.

**Comment by DanySK** [comment]
Hi Jake,
currently the project builds, and I have also added it to the nightly build triggers. Should we close this? I believe it is not the place for discussing our issues with drone.io support.

**Comment by DanySK** [comment]
Closing
