### ISSUE TITLE
Generic hood operators

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis-Parser#7]
I was thinking that we are currently adopting a very rigid way for adding new hood operations, that is defining them in the parser, then adding support in the interpreter.
I am thinking that we should maybe just provide a hood\[PlusSelf\](fun, field) operation, and provide other hood operators in a separate library.

e.g. minHood would become:
```
def minHood(field) {
    hood((a, b) -> { if (a.compareTo(b) < 0) { a } else { b }}, field)
}
```

Another possibility is to keep the current set of hood operators as builtins and add this one for future additions. @jakebeal and @mviroli, which is your opinion?

**Comment by mviroli** [comment]
the hood function must also have a further argument, the identity, i.e., 
the element E that you return if there are no neighbours, and such that 
it is an identify for the binary function -- Infinity for minHood, 0 for 
sumHood,..

On 30/07/2015 16:58, Danilo Pianini wrote:
> I was thinking that we are currently adopting a very rigid way for
> adding new hood operations, that is defining them in the parser, then
> adding support in the interpreter.
> I am thinking that we should maybe just provide a hoodPlusSelf
> operation, and provide other hood operators in a separate library.
>
> e.g. minHood would become:
>
> |def minHood(field) {
>      hood((a, b) -> { if (a.compareTo(b) < 0) { a } else { b }}, field)
> }
> |
>
> Another possibility is to keep the current set of hood operators as
> builtins and add this one for future additions. @jakebeal
> <https://github.com/jakebeal> and @mviroli <https://github.com/mviroli>,
> what is your opinion?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Protelis/Protelis-Parser/issues/7>.
>

-- 
Dott. Ing. Mirko Viroli, PhD
Associate Professor
DISI, Alma Mater Studiorum - Università di Bologna, Cesena
via Sacchi 3, Tel.: +39 0547 338846
via Venezia 52, Tel.: +39 0547 339216
47521 Cesena (FC)
mailto:  mirko.viroli "at" unibo.it
http://apice.unibo.it/xwiki/bin/view/MirkoViroli/

**Comment by jakebeal** [comment]
This is a very good idea.  I think that we should do it.  

Interestingly, this actually brings us back to how Proto originally did things long ago. The current system then emerged from the lack of first-class functions, which meant that we had to build macros in the compiler rather than a library.

**Comment by DanySK** [comment]
I agree with @mviroli, also the identity must be provided.
If we all agree, so be it :+1:
